name: bank_dwh
version: '1.0'
config-version: 2

profile: bank_dwh_profile

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  bank_dwh:
    stg:
      materialized: view
    raw:
      materialized: table
    ods:
      materialized: incremental
