bank_dwh_profile:
  target: dev
  outputs:
    dev:
      type: clickhouse
      threads: 1
      host: "{{ env_var('CH_HOST') }}"
      port: "{{ env_var('CH_PORT') }}"
      user: "{{ env_var('CH_USER') }}"
      password: "{{ env_var('CH_PASS') }}"
      database: bank_dwh
