bank_dwh_profile:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: airflow
      host: "{{ env_var('CH_HOST') }}"
      port: 9000
      user: "{{ env_var('CH_USER') }}"
      password: "{{ env_var('CH_PASS') }}"
      database: airflow
